class ComBase():
    def __init__(self,products_info,
                    com_quancheng,
                    com_faren ,
                    com_zhuceziben,
                    com_chenglishjian,
                    com_gongsileixing ,
                    com_dizhi,
                    com_gongsimingcheng,
                    com_gongsimingcheng2 ,
                    com_rongzilunci ,
                    com_zhucemingcheng,
                    com_guanwang ,
                    com_webwangzhi,
                    com_weixin ,
                    com_chengliyu,
                    com_state ,
                    com_guimo
    ):
        self.products_info = products_info
        self.com_quancheng = com_quancheng,
        self.com_faren = com_faren ,
        self.com_zhuceziben = com_zhuceziben,
        self.com_chenglishjian = com_chenglishjian,
        self.com_gongsileixing = com_gongsileixing,
        self.com_dizhi = com_dizhi,
        self.com_gongsimingcheng = com_gongsimingcheng,
        self.com_gongsimingcheng2 = com_gongsimingcheng2,
        self.com_rongzilunci = com_rongzilunci,
        self.com_zhucemingcheng = com_zhucemingcheng,
        self.com_guanwang = com_guanwang,
        self.com_webwangzhi = com_webwangzhi,
        self.com_weixin = com_weixin,
        self.com_chengliyu = com_chengliyu,
        self.com_state = com_state,
        self.com_guimo = com_guimo

